version: '3.8'

services:
  api:
    build: ./minibank-api
    ports:
      - "8080:8080"
    depends_on:
      - db

  # frontend:
  #   build: ./minibank-web
  #   ports:
  #     - "5173:5173"
  #   command: npm run dev
  #   volumes:
  #     - ./minibank-web:/app
  #   working_dir: /app

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: minibank
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
